### ISSUE TITLE
Suggestion: store OSM data and map coordinates for advanced users

### ISSUE THREAD

**Issue by OlaHaldor** [iwatkot/maps4fs#2]
I want to suggest you store the OSM data which is used, and that the exact corner coordinates used for the h eightmap.
This would allow advanced users to download higher resolution heightmaps from other sources and match the coordinates exactly. Plus the OSM data can be used to create curves for roads, and building outlines can be used to either generate buildings or as a basis for custom modeling in perfect scale.

All I'd ask for is the tool stores this data in a separate folder next to  moddesc.xml for instance.

**Comment by iwatkot** [comment]
@OlaHaldor, hey!
Thanks for the suggestion. I'll add some metrics and additional info to the output folder in the next release.
Meanwhile, maybe you know some free services to download high-res heightmaps, so I can add it into the repo?

Sincerely

**Comment by OlaHaldor** [comment]
Sadly I don't know of any sources which will allow streaming data. I 
only know of hoydedata.no which covers all of Norway, and you have to 
order either geotiff or point clouds.

**Comment by iwatkot** [comment]
I've added some information about generation in the latest release.
Learn more about current info in README: https://github.com/iwatkot/maps4fs?tab=readme-ov-file#info-sequence

P.S. I launched the bot again, you can try it.
