### ISSUE TITLE
[Suggestion/Bug] Add a setting for when generating just a large flatter area to set the blur to 1

### ISSUE THREAD

**Issue by Willow-6855** [iwatkot/maps4fs#24]
Add a setting for when generating just a large flatter area to set the blur to 1. as anything high then 3 with a large flat terrain just becomes bumping

**Comment by Willow-6855** [comment]
It happened with a 2X map and it produce sharp/jagged terrain

**Comment by Willow-6855** [comment]
Cords: 40.06645, -85.91060

Size: 2X

any blur over 3 causes it to produce sharp/jagged terrain in GE

**Comment by Willow-6855** [comment]
DEM was left on default

**Comment by iwatkot** [comment]
@ Willow-6855, I can not reproduce the issue. It looks fine on the same coordinates with the default advanced settings.

**Comment by iwatkot** [comment]
Closed as staled.
