### ISSUE TITLE
Can't open map in giants editor

### ISSUE THREAD

**Issue by flexer89** [iwatkot/maps4fs#28]
Hi, after downloading the map I can'y open it in giants editor, it freezes for 5 seconds and then automaitcally closes.
I tried to download different map sizes, for different games (fs25/fs22) and different coordinates even tried to run locally as a container and everytime I encounter on this problem. Maybe I use wrong GE version (9.0.6)?

Please help. Thank you 💯

**Comment by iwatkot** [comment]
@flexer89, to open the FS25 map you need GE v10.
To open the FS22 map you need GE v9.

Otherwise, it won't work.

Sincerely
