### ISSUE TITLE
Missing structures

### ISSUE THREAD

**Issue by Manasx100** [iwatkot/maps4fs#4]
When I try to generate a map using the local method or telegram app it just shows something like this
![photo_2024-05-28_16-29-25](https://github.com/iwatkot/maps4fs/assets/80171692/d8011518-7a96-4bd1-bab1-29839d8d73ab)
On almost every coordinate I tried except the example one in the bot
This picture used 55.70117149841207, 21.145143669369897  ,4096x4096 ,For hills .
![photo_2024-05-28_17-39-35](https://github.com/iwatkot/maps4fs/assets/80171692/e41020ab-5eb8-465e-8c34-876a243a9104)
And this one used the same except coordinates 55.703002679267, 21.14383789155618 .

**Comment by iwatkot** [comment]
@Manasx100, hello, and thanks for the report!
I can confirm that this is a recurring bug. I'll investigate it and get back to you with updates.

Sincerely

**Comment by iwatkot** [comment]
The bug was identified and will be fixed in the upcoming release.

![image](https://github.com/iwatkot/maps4fs/assets/118521851/05a63f23-9e04-4713-8de9-4da8575be871)
![image](https://github.com/iwatkot/maps4fs/assets/118521851/cc7f51a9-e209-41bf-9aa7-5551004fa3a1)

**Comment by iwatkot** [comment]
@Manasx100 the new release is ready.
The bot was also updated, you can use it now for your coordinates.

Thank you for the report once again and let me know if you have any issues.
Sincerely
