### ISSUE TITLE
[Suggestion] Make DEM multiplier a float instead of an integer

### ISSUE THREAD

**Issue by YipNZ** [iwatkot/maps4fs#43]
Can the DEM Multipler be made a float instead of an integer? Currently we can choose between 0 and 1, 2, etc.. Being able to use 0.9, for example, would help make some terrains usable as the Blur option tend to just flatten everything out.

Cheers.

**Comment by iwatkot** [comment]
@YipNZ, hello!

This feature will be removed and the multiplier will be rolled back to an integer due to higher RAM usage for float transformations which leads to community app crashes.

You can use the Python version if you need it.

Regards
