### ISSUE TITLE
Error running app

### ISSUE THREAD

**Issue by beemer328** [iwatkot/maps4fs#47]
Error running app    https://maps4fs.streamlit.app/

**Comment by Fs-Olli** [comment]
@beemer328 I´m having this problem too mention me if the problem is fixed

**Comment by iwatkot** [comment]
@beemer328 @Fs-Olli 

Note, that all issues regarding the availability of the StreamLit community app will be closed automatically. Please use the [Docker version](https://github.com/iwatkot/maps4fs?tab=readme-ov-file#option-2-docker-version) of the tool. Thank you!
