### ISSUE TITLE
Map generator 

### ISSUE THREAD

**Issue by DutchOpsGaming** [iwatkot/maps4fs#66]
Hey hello want to let you know , we cant use your @maps4fsbot no more sinds late last night 16/12/24 .

Error running app. If this keeps happening, please [contact support](https://github.com/iwatkot/maps4fs/issues/new).

So is ther a way we can use it or it needs any fix ???
 Thank you

**Comment by iwatkot** [comment]
@DutchOpsGaming, hey!

The Telegram Bot was deprecated and turned off.
